In [2]:
import re
import sqlite3
import requests
import pandas as pd

headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'accept-language': 'en-US,en;q=0.9',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/144.0.0.0 Safari/537.36',
}

# 32 available markets
MARKETS = [
    'atlanta', 'birmingham', 'charleston', 'charlotte', 'chicago',
    'cincinnati', 'colorado-springs', 'columbus', 'dallas', 'denver',
    'fort-worth', 'ft-myers', 'greenville', 'houston', 'indianapolis',
    'jacksonville', 'kansas-city', 'las-vegas', 'louisville', 'memphis',
    'miami', 'nashville', 'oklahoma-city', 'orlando', 'overland-park',
    'phoenix', 'raleigh-durham', 'san-antonio', 'st-louis', 'tampa',
    'tucson', 'winston-salem',
]

print('Available markets:', ', '.join(MARKETS))

Available markets: atlanta, birmingham, charleston, charlotte, chicago, cincinnati, colorado-springs, columbus, dallas, denver, fort-worth, ft-myers, greenville, houston, indianapolis, jacksonville, kansas-city, las-vegas, louisville, memphis, miami, nashville, oklahoma-city, orlando, overland-park, phoenix, raleigh-durham, san-antonio, st-louis, tampa, tucson, winston-salem

In [4]:
metro_location = input('Enter market (e.g. houston, atlanta, dallas): ').strip().lower()

if metro_location not in MARKETS:
    print(f'Warning: "{metro_location}" not in known markets list')

print(f'Scraping FirstKey Homes: {metro_location}')

Scraping FirstKey Homes: houston

In [5]:
# Fetch the rental page — property data is embedded in the HTML
# The site uses S2A JIT framework with Socket.IO for dynamic loading,
# but the server-side rendered HTML includes property records.
# Note: The SSR may not include all listings (e.g. 48 of 131 for Houston).
# The full dataset requires WebSocket interaction which is not practical here.

url = 'https://www.firstkeyhomes.com/rental-homes/' + metro_location
response = requests.get(url, headers=headers)
response.raise_for_status()

html = response.text
print(f'Page size: {len(html):,} bytes')

# Extract property records from embedded S2A data
# The HTML uses \&q; as escaped quote characters
# Each record starts with: {\&q;_jsonit\&q;:{\&q;_meta\&q;:{\&q;id\&q;:\&q;{ID}\&q;
marker = '{\\&q;_jsonit\\&q;:{\\&q;_meta\\&q;:{\\&q;id\\&q;:\\&q;'
parts = html.split(marker)
print(f'Found {len(parts) - 1} embedded data blocks')

seen_ids = set()
records = []

for part in parts[1:]:
    # Only process blocks that have property data (address field)
    if '\\&q;address\\&q;:\\&q;' not in part:
        continue

    # The _meta.id is the first value right after the split marker
    meta_id = part.split('\\&q;')[0]

    # Deduplicate by _meta.id (same as voyager field, used in URL)
    if meta_id in seen_ids:
        continue
    seen_ids.add(meta_id)

    # Truncate at next record marker for regex safety
    end = part.find('{\\&q;_jsonit\\&q;:{\\&q;_meta\\&q;:{\\&q;id\\&q;:\\&q;', 10)
    if end == -1:
        end = min(len(part), 8000)
    chunk = part[:end]

    def get_str(field):
        m = re.search(r'\\&q;' + field + r'\\&q;:\\&q;([^\\]*)\\&q;', chunk)
        return m.group(1) if m else ''

    def get_num(field):
        m = re.search(r'\\&q;' + field + r'\\&q;:([\d.]+)', chunk)
        return m.group(1) if m else ''

    def get_bool(field):
        m = re.search(r'\\&q;' + field + r'\\&q;:(true|false)', chunk)
        return m.group(1) == 'true' if m else False

    # Extract coordinates from location.coordinates:[lng,lat]
    coords_match = re.search(
        r'\\&q;coordinates\\&q;:\[(-?[\d.]+),(-?[\d.]+)\]', chunk
    )
    lng = coords_match.group(1) if coords_match else ''
    lat = coords_match.group(2) if coords_match else ''

    short_name = get_str('shortName')

    records.append({
        'property_id': meta_id,
        'address': get_str('address'),
        'city': get_str('city'),
        'state': get_str('state'),
        'zip': get_str('zip'),
        'bedrooms': get_num('bedrooms'),
        'bathrooms': get_num('bathrooms'),
        'sqft': get_num('area'),
        'rent': get_num('rent'),
        'available_at': get_str('availableAt'),
        'market': get_str('market'),
        'unit_status': get_num('unitStatus'),
        'self_tour_status': get_num('selfTourStatus'),
        'special_offer': get_bool('specialOffer'),
        'lat': lat,
        'lng': lng,
        'short_name': short_name,
        'link': 'https://www.firstkeyhomes.com/homes-for-rent/'
                + meta_id + '/' + short_name,
        'metro_location': metro_location,
    })

# Check total count from embedded metadata
decoded = html.replace('\\&q;', '"')
count_match = re.search(r'"count":(\d+)', decoded)
total_count = int(count_match.group(1)) if count_match else '?'

print(f'Extracted {len(records)} unique properties (total in market: {total_count})')
if isinstance(total_count, int) and len(records) < total_count:
    print(f'Note: {total_count - len(records)} additional listings load via WebSocket and are not captured here')

Page size: 1,195,641 bytes
Found 2460 embedded data blocks
Extracted 48 unique properties (total in market: 146)
Note: 98 additional listings load via WebSocket and are not captured here

In [10]:
re

48

In [11]:
df = pd.DataFrame(records)

dupes = df.duplicated(subset='property_id', keep='first').sum()
print(f'Duplicate rows: {dupes}')
df = df.drop_duplicates(subset='property_id', keep='first')

df.info()
df.head()

Duplicate rows: 0
<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   property_id       48 non-null     str
 1   address           48 non-null     str
 2   city              48 non-null     str
 3   state             48 non-null     str
 4   zip               48 non-null     str
 5   bedrooms          48 non-null     str
 6   bathrooms         48 non-null     str
 7   sqft              48 non-null     str
 8   rent              48 non-null     str
 9   available_at      48 non-null     str
 10  market            48 non-null     str
 11  unit_status       48 non-null     str
 12  self_tour_status  48 non-null     str
 13  special_offer     48 non-null     bool
 14  lat               48 non-null     str
 15  lng               48 non-null     str
 16  short_name        48 non-null     str
 17  link              48 non-null     str
 18  metro_location    48 non-null     str
dtypes: bool(1), str(18)
memory usage: 6.9 KB

,property_id,address,city,state,zip,bedrooms,bathrooms,sqft,rent,available_at,market,unit_status,self_tour_status,special_offer,lat,lng,short_name,link,metro_location
0,94398701,439 Sky Ridge Drive,Alvin,TX,77511,4,2.5,2295,2580,2026-03-13T12:00:00.000Z,houston,1,1,False,29.4668,-95.2547,439-sky-ridge-drive-alvin-tx-77511,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
1,93218701,321 Lakeway Circle,Anahuac,TX,77514,3,3,2109,2155,2026-02-27T12:00:00.000Z,houston,2,1,False,29.7883,-94.6654,321-lakeway-circle-anahuac-tx-77514,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
2,44358701,4435 Sprangletop Avenue,Baytown,TX,77521,4,2.5,2240,1815,2026-01-14T12:00:00.000Z,houston,3,0,False,29.8184,-94.9928,4435-sprangletop-avenue-baytown-tx-77521,https://www.firstkeyhomes.com/homes-for-rent/4...,houston
3,25588701,2558 Doral Drive,Baytown,TX,77523,4,3,2487,2440,2026-04-08T12:00:00.000Z,houston,1,1,False,29.7099,-94.9572,2558-doral-drive-baytown-tx-77523,https://www.firstkeyhomes.com/homes-for-rent/2...,houston
4,46128701,4612 Ironwood Drive,Baytown,TX,77521,4,2.5,2664,2350,2026-04-20T12:00:00.000Z,houston,1,1,False,29.7681,-94.991,4612-ironwood-drive-baytown-tx-77521,https://www.firstkeyhomes.com/homes-for-rent/4...,houston

In [14]:
df.head(50)

,property_id,address,city,state,zip,bedrooms,bathrooms,sqft,rent,available_at,market,unit_status,self_tour_status,special_offer,lat,lng,short_name,link,metro_location
0,94398701,439 Sky Ridge Drive,Alvin,TX,77511,4,2.5,2295,2580,2026-03-13T12:00:00.000Z,houston,1,1,False,29.4668,-95.2547,439-sky-ridge-drive-alvin-tx-77511,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
1,93218701,321 Lakeway Circle,Anahuac,TX,77514,3,3,2109,2155,2026-02-27T12:00:00.000Z,houston,2,1,False,29.7883,-94.6654,321-lakeway-circle-anahuac-tx-77514,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
2,44358701,4435 Sprangletop Avenue,Baytown,TX,77521,4,2.5,2240,1815,2026-01-14T12:00:00.000Z,houston,3,0,False,29.8184,-94.9928,4435-sprangletop-avenue-baytown-tx-77521,https://www.firstkeyhomes.com/homes-for-rent/4...,houston
3,25588701,2558 Doral Drive,Baytown,TX,77523,4,3,2487,2440,2026-04-08T12:00:00.000Z,houston,1,1,False,29.7099,-94.9572,2558-doral-drive-baytown-tx-77523,https://www.firstkeyhomes.com/homes-for-rent/2...,houston
4,46128701,4612 Ironwood Drive,Baytown,TX,77521,4,2.5,2664,2350,2026-04-20T12:00:00.000Z,houston,1,1,False,29.7681,-94.991,4612-ironwood-drive-baytown-tx-77521,https://www.firstkeyhomes.com/homes-for-rent/4...,houston
5,92158701,215 Brazos Drive,Baytown,TX,77523,5,3,3139,3210,2026-04-22T12:00:00.000Z,houston,1,1,False,29.8243,-94.824,215-brazos-drive-baytown-tx-77523,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
6,70068703,7006 ORCHID St,Baytown,TX,77521,3,2,1620,2025,2026-04-23T12:00:00.000Z,houston,1,1,False,29.7986,-95.0353,7006-orchid-st-baytown-tx-77521-0,https://www.firstkeyhomes.com/homes-for-rent/7...,houston
7,14704602,14701 Country Club Road,Beaumont,TX,77705,3,2,1619,1825,2026-02-11T12:00:00.000Z,houston,3,0,False,29.8698,-94.1407,14701-country-club-road-beaumont-tx-77705,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
8,14728703,14725 Country Club Road,Beaumont,TX,77705,3,2.5,1659,1780,2026-02-24T12:00:00.000Z,houston,3,0,False,29.8698,-94.1402,14725-country-club-road-beaumont-tx-77705,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
9,92458702,245 Road 5102F,Cleveland,TX,77327,3,2,1421,1700,2026-04-02T12:00:00.000Z,houston,1,0,False,30.161,-95.093,245-road-5102f-cleveland-tx-77327,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
10,90268702,26 Road 5102F,Cleveland,TX,77327,4,2,1761,1920,2026-04-24T12:00:00.000Z,houston,1,1,False,30.1639,-95.0934,26-road-5102f-cleveland-tx-77327,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
11,26188701,2618 N Woodloch Street,Conroe,TX,77385,4,2,2041,1750,2026-01-30T12:00:00.000Z,houston,3,0,False,30.2182,-95.4153,2618-n-woodloch-street-conroe-tx-77385,https://www.firstkeyhomes.com/homes-for-rent/2...,houston
12,28548701,2854 Cayden Creek Way,Conroe,TX,77304,3,2,1672,2245,2026-03-10T12:00:00.000Z,houston,2,0,False,30.2928,-95.4889,2854-cayden-creek-way-conroe-tx-77304,https://www.firstkeyhomes.com/homes-for-rent/2...,houston
13,16988701,16985 Valiant Oak Street,Conroe,TX,77385,3,2,1760,1815,2026-03-13T12:00:00.000Z,houston,1,0,False,30.2104,-95.4281,16985-valiant-oak-street-conroe-tx-77385-0,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
14,17648701,17640 Cedar Crest Drive,Conroe,TX,77306,4,2.5,1784,1890,2026-04-14T12:00:00.000Z,houston,1,1,False,30.3326,-95.2974,17640-cedar-crest-drive-conroe-tx-77306,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
15,90018701,1 Midwood Cir,Conroe,TX,77301,3,2,1936,2095,2026-04-15T12:00:00.000Z,houston,1,1,False,30.2974,-95.4456,1-midwood-cir-conroe-tx-77301-0,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
16,59318701,5931 Golden Cove Rd,Cove,TX,77523,3,2.5,1882,1990,2026-03-23T12:00:00.000Z,houston,1,1,False,29.8137,-94.8324,5931-golden-cove-rd-cove-tx-77523,https://www.firstkeyhomes.com/homes-for-rent/5...,houston
17,59078701,5907 Treasure Cove,Cove,TX,77523,3,2,1166,1795,2026-04-08T12:00:00.000Z,houston,1,1,False,29.8141,-94.8338,5907-treasure-cove-cove-tx-77523,https://www.firstkeyhomes.com/homes-for-rent/5...,houston
18,93318701,331 American Black Bear Drive,Crosby,TX,77532,4,2,1856,1810,2026-02-15T12:00:00.000Z,houston,3,0,False,29.8886,-95.0581,331-american-black-bear-drive-crosby-tx-77532,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
19,16426801,16426 Rudder Drive,Crosby,TX,77532,4,2.5,2349,2315,2026-04-02T12:00:00.000Z,houston,1,1,False,29.9229,-95.0996,16426-rudder-drive-crosby-tx-775320,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
20,15728702,15726 W Chamfer Way,Crosby,TX,77532,5,2.5,3082,2635,2026-04-07T12:00:00.000Z,houston,1,1,False,29.9084,-95.0832,15726-w-chamfer-way-crosby-tx-77532,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
21,15328701,15327 Wild Timber Trail,Cypress,TX,77433,4,3,2704,2670,2026-03-13T12:00:00.000Z,houston,1,1,False,30.0037,-95.7539,15327-wild-timber-trail-cypress-tx-77433,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
22,21908701,21902 Richard Glen Drive,Cypress,TX,77433,3,2,1980,2510,2026-03-18T12:00:00.000Z,houston,1,1,False,30.0096,-95.7653,21902-richard-glen-drive-cypress-tx-774330,https://www.firstkeyhomes.com/homes-for-rent/2...,houston
23,78718701,7871 Ashland Springs Lane,Cypress,TX,77433,3,2,1676,1820,2026-03-18T12:00:00.000Z,houston,1,0,False,29.8922,-95.7111,7871-ashland-springs-lane-cypress-tx-77433-0,https://www.firstkeyhomes.com/homes-for-rent/7...,houston
24,14108701,14103 White Oak Gardens Drive,Cypress,TX,77429,5,3,2721,2770,2026-04-08T12:00:00.000Z,houston,1,1,False,29.9317,-95.634,14103-white-oak-gardens-drive-cypress-tx-77429,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
25,15408708,15406 Boulder Hollow Ln,Cypress,TX,77429,3,2,1939,2230,2026-04-20T12:00:00.000Z,houston,1,4,False,30.0002,-95.6714,15406-boulder-hollow-ln-cypress-tx-77429,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
26,18018701,1801 WHITEBRIAR DR,Deer Park,TX,77536,3,2,1396,2095,2026-04-14T12:00:00.000Z,houston,1,1,False,29.6945,-95.1397,1801-whitebriar-dr-deer-park-tx-77536-0,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
27,25058701,2505 Texas Ave,Dickinson,TX,77539,4,2,2007,1650,2025-12-04T12:00:00.000Z,houston,3,0,False,29.4774,-95.0419,2505-texas-ave-dickinson-tx-77539-0,https://www.firstkeyhomes.com/homes-for-rent/2...,houston
28,51318701,5131 Whittier Oaks Drive,Friendswood,TX,77546,3,2,1834,1890,2026-02-10T12:00:00.000Z,houston,3,0,False,29.5352,-95.186,5131-whittier-oaks-drive-friendswood-tx-77546-0,https://www.firstkeyhomes.com/homes-for-rent/5...,houston
29,16108705,16106 David Glen Drive,Friendswood,TX,77546,3,2,1480,2115,2026-03-31T12:00:00.000Z,houston,1,1,False,29.5326,-95.1858,16106-david-glen-drive-friendswood-tx-77546,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
30,93108701,9310 Westacre Place,Houston,TX,77083,3,2.5,1659,1880,2026-01-28T12:00:00.000Z,houston,3,0,False,29.6794,-95.6339,9310-westacre-place-houston-tx-77083-0,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
31,14118706,14115 Ivy Bluff Court,Houston,TX,77062,4,2.5,2720,2320,2026-01-31T12:00:00.000Z,houston,3,0,False,29.5906,-95.1447,14115-ivy-bluff-court-houston-tx-77062,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
32,18218702,18210 Widcombe Drive,Houston,TX,77084,4,2.5,2773,2165,2026-02-02T12:00:00.000Z,houston,3,0,False,29.8388,-95.6805,18210-widcombe-drive-houston-tx-77084-0,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
33,14708701,14703 Saint Cloud Drive,Houston,TX,77062,4,2.5,1839,2245,2026-02-03T12:00:00.000Z,houston,3,0,False,29.5824,-95.137,14703-saint-cloud-drive-houston-tx-77062,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
34,12438701,12433 LEDGER LN,Houston,TX,77015,3,1,1296,1350,2026-02-06T12:00:00.000Z,houston,3,0,False,29.755,-95.2144,12433-ledger-ln-houston-tx-77015-0,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
35,82228702,8222 Streamside Drive,Houston,TX,77088,3,2,1726,1770,2026-02-13T12:00:00.000Z,houston,3,0,False,29.8899,-95.4676,8222-streamside-drive-houston-tx-77088,https://www.firstkeyhomes.com/homes-for-rent/8...,houston
36,27228701,2722 Skyview Long Drive,Houston,TX,77047,3,2,1539,2140,2026-02-15T12:00:00.000Z,houston,3,0,False,29.6262,-95.3811,2722-skyview-long-drive-houston-tx-77047,https://www.firstkeyhomes.com/homes-for-rent/2...,houston
37,15918702,15915 VISTA DEL MAR DR,Houston,TX,77083,4,3,2165,1890,2026-02-17T12:00:00.000Z,houston,3,0,False,29.7015,-95.6668,15915-vista-del-mar-dr-houston-tx-77083-0,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
38,49278701,4927 Kilkenny Dr,Houston,TX,77048,3,2,1362,1470,2026-02-17T12:00:00.000Z,houston,3,4,False,29.6252,-95.3511,4927-kilkenny-dr-houston-tx-77048-0,https://www.firstkeyhomes.com/homes-for-rent/4...,houston
39,97028701,9702 Desert Flower Lane,Houston,TX,77086,3,2,1393,1975,2026-02-22T12:00:00.000Z,houston,3,0,False,29.9217,-95.5026,9702-desert-flower-lane-houston-tx-77086,https://www.firstkeyhomes.com/homes-for-rent/9...,houston
40,17118705,17118 Carshalton Court,Houston,TX,77084,3,2,1516,1790,2026-02-23T12:00:00.000Z,houston,3,1,False,29.8632,-95.6663,17118-carshalton-court-houston-tx-77084,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
41,12918706,12919 Belmont Legend Court,Houston,TX,77047,5,3,2610,2555,2026-03-10T12:00:00.000Z,houston,2,1,False,29.6193,-95.4086,12919-belmont-legend-court-houston-tx-77047,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
42,15238703,1523 Nichole Woods Drive,Houston,TX,77047,3,2.5,1558,1810,2026-03-12T12:00:00.000Z,houston,1,0,False,29.6217,-95.3927,1523-nichole-woods-drive-houston-tx-77047,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
43,12808704,12806 Lilac Stone Court,Houston,TX,77044,3,2.5,1178,1645,2026-03-18T12:00:00.000Z,houston,1,1,False,29.8658,-95.2037,12806-lilac-stone-court-houston-tx-77044,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
44,77748701,7774 High Village Drive,Houston,TX,77095,3,2.5,1556,1950,2026-03-18T12:00:00.000Z,houston,1,1,False,29.895,-95.6556,7774-high-village-drive-houston-tx-77095-0,https://www.firstkeyhomes.com/homes-for-rent/7...,houston
45,32158702,3215 Holly Thicket Dr,Houston,TX,77042,3,2.5,2376,2715,2026-03-18T12:00:00.000Z,houston,1,1,False,29.7301,-95.5505,3215-holly-thicket-dr-houston-tx-77042,https://www.firstkeyhomes.com/homes-for-rent/3...,houston
46,13838702,13830 Purplemartin Street,Houston,TX,77083,3,2.5,1972,2040,2026-03-23T12:00:00.000Z,houston,1,1,False,29.6843,-95.6294,13830-purplemartin-street-houston-tx-77083-0,https://www.firstkeyhomes.com/homes-for-rent/1...,houston
47,33158701,3315 Vega Street,Houston,TX,77088,3,2,1800,1845,2026-03-24T12:00:00.000Z,houston,1,0,False,29.8816,-95.4566,3315-vega-street-houston-tx-77088,https://www.firstkeyhomes.com/homes-for-rent/3...,houston

In [5]:
df.to_csv('firstkey_homes.csv', index=False)
print(f'Saved {len(df)} rows to firstkey_homes.csv')

Saved 48 rows to firstkey_homes.csv

In [6]:
conn = sqlite3.connect('firstkey_homes.db')
df.to_sql('listings', conn, if_exists='replace', index=False)
print(f'Wrote {len(df)} rows to firstkey_homes.db -> listings table')
conn.close()

Wrote 48 rows to firstkey_homes.db -> listings table